apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: gestion-etudiants
type: Opaque
stringData:
  DB_PASSWORD: root
  JWT_SECRET: changeThisSecretKeyInProductionEnvironmentPleaseMakeItLongEnough
